version: '3.8'

services:
  web:
    image: easypanel-nextjs:0.0.1
    build:
      context: ../../
      dockerfile: docker/production/Dockerfile
      target: development
    container_name: en_dev
    env_file:
      - ../../.env.development
    ports:
      - 3000:3000
    volumes:
      # - .:/app
      - ../../data:/data
    restart: unless-stopped
    command: sh -c "sh ./scripts/run.sh"
