version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    # depends_on:
    #   db:
    #     condition: service_healthy
    #   redis:
    #     condition: service_started
    image: easypanel-nextjs
    container_name: nextjs-sqlite-docker
    env_file:
      - .env.production
    ports:
      - 3000:3000
    volumes:
      - ./data:/data
  # migration:
  #   build:
  #     context: .
  #     dockerfile: docker/migrations/Dockerfile
  #   image: sqlite-migrations
  #   depends_on:
  #     - web
