version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: easypanel-nextjs-sqlite
    container_name: nextjs-sqlite-docker
    env_file:
      - .env.production
    ports:
      - 3000:3000
    volumes:
      - ./data:/data
