version: '3.8'

services:
  web:
    image: easypanel-nextjs:0.0.1
    build:
      context: ../../
      dockerfile: docker/production/Dockerfile
    container_name: en_prod
    env_file:
      - ../../.env.production
    ports:
      - 3000:3000
    volumes:
      - ../../data:/data
    restart: unless-stopped
